# Spring Boot lit automatiquement SPRING_DATASOURCE_URL etc. depuis l'environnement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Thymeleaf
spring.thymeleaf.cache=true
spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/

# Port
server.port=${PORT:8080}

# Logging
logging.level.cm.agriprix=INFO